doc/content/end-user-documentation/html.rst, lona/html/data_binding/inputs.py, lona/html/data_binding/select.py
Fixes #20.
Users of `TextInput` and successors (`TextArea`, `CheckBox`) expect to see `input_event.node` to be `TextInput` itself, not its attribute `.input_node`.
The same if for `Select`.
So need to update it before bubble up.
=> Redefine `input_event.node` in `handle_input_event`

lona/server.py
Argument `sync` was removed some time ago.
@fscherf As far as I understand here we don't need `wait=False`. Am I right?
=> Fix typo in argument name

lona/html/node.py
If I'm right, they are not used anymore (after 83b35ff42ef49513ba41f12c4489a108d3365f89).
=> Remove old methods `Node._xxx_patches`

lona/html/data_binding/inputs.py, lona/html/data_binding/select.py
Before that it was possible to return empty string instead of `False`
=> html: data binding: always return bool for node.disabled

lona/html/attribute_dict.py, lona/html/data_binding/inputs.py, lona/html/data_binding/select.py, lona/html/node.py, lona/html/nodes.py, tests/test_0001_html.py
* Added the second optional argument to `AttributeDict.pop`. Now `node.attributes.pop('foo', 'bar')=='bar'` if there is no `foo` in attributes.
* Now `del node.attributes['foo']` do nothing if there is no `foo` in attributes. Before `KeyError` raised.
=> html: attributes: add default to pop() and make del silent

lona/html/attribute_dict.py, lona/html/attribute_list.py, lona/html/node_list.py, lona/html/widgets.py
Before this change `__iter__` was used to execute `"disabled" in node.attributes`. And there was a chance to get `RuntimeError: dictionary changed size during iteration` in concurrent execution.
Now the whole operation is protected with lock.
=> html: implement __contains__ with lock

lona/html/data_binding/inputs.py, lona/html/data_binding/select.py, test_project/views/events/callbacks.py
TextInput.handle_change gets called at the correct time, but the value of
TextInput.value gets not set before, which is counter-intuitive.
This patch sets TextInput.value in TextInput.handle_input_event() and then
calls TextInput.handle_change(). This patch also adds a test view for this
feature to the test project.
=> html: data binding: fix TextInput.handle_change

lona/html/parsing.py, lona/middleware_controller.py, lona/response_parser.py, lona/server.py, lona/static_file_loader.py, lona/view_runtime_controller.py
It also may increase performance a bit because of lazy formatting. `repr` may even not be called depending on selected log level.
=> cosmetics: use %r for logging instead of repr()

lona/html/nodes.py
Since we restructured click and change events, Submit and Reset catch their own click events, which breaks traditional froms
(test project url: /view-types/form-view/)
=> html: Submit, Reset: remove lona click events

pytest.ini, tests/test_0001_html.py
See https://pytest-dependency.readthedocs.io/en/stable/configuration.html#configuration-file-options
=> tests: remove unnecessary mark.dependency

lona/html/parsing.py, tests/test_0001_html.py
Before wrong dict was used to get node class. That caused incorrect parsing of `input` HTML element. `TextInput` was used always despite `type` attribute.
=> html: parsing: fix input type definition

doc/content/end-user-documentation/views.rst, lona/html/node.py, lona/html/text_node.py
Previously nodes had a special ``__eq__()`` method that made high level comparisons
between nodes possible.
Div(a=1) == Div(a=1) -> True
Div(a=1) == Div(b=1) -> False
This feature was intended to be used for testing purposes in the future.
The problem with this implementation is that methods like list.index() or
list.remove() use ``__eq__()`` to find an list item.
d1 = Div()
d2 = Div()
l = [d1, d2]
l.index(d1) -> 0
l.index(d2) -> 0
This breaks patch generating and a lot of potential application code.
@maratori Could you review this?
=> html: fix node list operations

pytest.ini, tests/conftest.py, tests/test_0001_html.py, tests/test_0100_components.py, tests/test_routing.py
Here is why we had a long test functions: https://github.com/lona-web-org/lona/pull/61#discussion_r702608329.
Now we use test class methods in combination with custom `@pytest.mark.incremental()` from [here](https://docs.pytest.org/en/latest/example/simple.html#incremental-testing-test-steps).
The only downside is that we can't mark that test depends on all methods in class, but have to list them all (see RKrahl/pytest-dependency#55).
=> tests: split long tests to class methods

lona/html/parsing.py, tests/test_0001_html.py
Before this change slash was not optional in self-closing tags.
=> html: parsing: optional slash in self-closing tags

tox.ini
Let's use [flake8-2020](https://github.com/asottile/flake8-2020) to check for misuse of `sys.version` or `sys.version_info`. May be important after Python 3.10.
=> lint: use flake8-2020 plugin

lona/html/data_binding/inputs.py
input_delay makes only sense with text inputs.
=> html: data binding: CheckBox: remove obsolete argument "input_delay"

lona/app.py, lona/command_line/handle_command_line.py
With these patches command line arguments can be used in Lona scripts.
``python lona_script.py --port=8081 --shell -O Foo=True``
=> scripts: add command line args

lona/app.py, lona/pytest.py
New function `eventually()` allows to wait for an expected state in tests. Iterator and context managers are used to be able repeating assertions.
Alternative approach is to accept function as an argument, and call it several times. But in this case user has to create a function inside test to make an assert. That's because `assert` is a statement and python doesn't allow it inside the `lambda`.
=> Add function `eventually()` for testing

lona/server.py, tests/test_view_stop_hooks.py
This PR adds a test for ``LonaView.on_stop`` and ``LonaView.on_cleanup``, and fixes a lockup between the server and the application code.
@maratori This does not fix the pytest+playwright lockup problem entirely, but it seems to improve the situation. Previously the tests froze, which now seems fixed. There is still a teardown problem sometimes, but we make it through the tests.
=> pytest: fix race condition

lona/html/widget_data.py
The payload of patches have to be full copies of the original values to prevent
changes to the payload after the patch got created.
Previously some patches contained the original list or dict. When the dict or
list changed, the patch payload changed implicitly.
=> fix(html): widget data: fix patch generating

.github/workflows/ci.yml, REQUIREMENTS.packaging.txt, lona/__init__.py, lona/logging.py, tests/REQUIREMENTS.lint.txt, tests/REQUIREMENTS.test.txt
Currently Lona has different dependencies for production, packaging, linting and testing. All import errors during these stages get ignored by a try except block in the Lona top level module. This worked ok until now, but it covers up real import errors in production.
This PR adds all dependencies to all environments and removes the code that ignores all import errors.
=> fix import errors on windows

lona/html/attribute_dict.py
Previously HTML representations looked like that:
<input data-lona-node-id="1" type=&quot;checkbox&quot; />
This was because the whole attribute string was quoted and not every attribute
value individually.
=> fix quoting in attribute dicts

lona/app.py
Without the return in the decorator the effect is that after
@app.route('/')
class MyView(LonaView):
...
the name `MyView` is bound to `None`, because the decorator syntax is just
a nice way to write:
class MyView(LonaView):
...
MyView = app.route('/')(MyView)
With the return added, `MyView` holds the class as expected.
=> app: return the class from the route decorator

doc/content/logo.svg
Some SVG renderers have bugs when two areas are right next to each other, and render each area on their own with antialiasing in relation to the background color. This has the disadvantageous effect that the background color bleeds through to the foreground, which in our case is mostly visible on dark backgrounds.
To fix this, add a 1px outline with the same color as the fill color to each of those areas, so that neighboring areas effectively overlap with each other, thereby covering the background.
Compare screenshots in Firefox before:
and after:
=> logo: fix bleeding background

lona/templating.py
This PR brings some cleanup for the Lona namespace in Jinja2 templates, and some new shortcuts
=> cleanup templating

pytest.ini, tox.ini
Previously the test root directory was configured both in the tox.ini and the
pytest.ini.
This patch moves the configuration into the pytest.ini and fixes some
whitespaces too.
=> ci(pytest): cleanup tox.ini and pytest.ini

lona/imports.py
Previously top-level import strings like 'json' were not possible.
=> feat(imports): add support for top-level imports

lona/html/document.py, lona/view_runtime.py
This patch fixes a bug, introduced in
ff7a0ab8316c ("fix(views): fix page titles on daemonized views")
ff7a0ab8316c introduced a new, optional argument to Document.apply, named
'title' and broke all code that calls Document.apply without named arguments.
=> fix(HTML): Document: fix incorrect usage of Document.apply

doc/content/cookbook/using-server-state.rst, doc/content/end-user-documentation/settings.rst, lona/default_settings.py, lona/server.py
Until now there was no way to fill ``server.state`` before the first actual view has been initialized.
With this changes it is now possible to define or load the initial values for ``server.state`` in the ``settings.py``.
In my case I have a rather simple web application that keeps track of a queue of images.
One view shows this queue of images ("frontend") and another view allows to configure this queue ("backend").
Both views share the current queue using ``server.state``. But: I did not find an elegant way to load my initial state:
I could do it in ``handle_request`` but this would mean code duplication between the views.
For me the best way to handle this is to allow the user to define the *initial_state* of the ``server.state``.
And since I can run arbitrary python-magic in …
=> server: Allow loading of state in settings

lona/command_line/run_server.py, lona/shell/commands/lona_connections.py, lona/shell/commands/lona_info.py, lona/shell/commands/lona_middlewares.py, lona/shell/commands/lona_routes.py, lona/shell/commands/lona_server_state.py, lona/shell/commands/lona_settings.py, lona/shell/commands/lona_static_files.py, lona/shell/commands/lona_templates.py, lona/shell/commands/lona_views.py
rlpython version prior to 0.10 had separate globals and locals. 0.10 merged
them into a global namespace named globals.
This patch changes all code that reads or writes repl.locals.
=> fix(shell): fix incompatibility with rlpython 0.10

doc/content/end-user-documentation/views.rst
In https://github.com/lona-web-org/lona/pull/223 I showed that I did not
understand that a custom pattern can be used to create a wildcard match.
This change updates the documentation to contain some more words about
custom patterns.
Signed-off-by: Chris Fiege <chris@tinyhost.de>
=> fix(doc): Show that custom URL-pattern can match any character

.github/dependabot.yml
As you can see, your dependecies are not updated.
Dependabot expects relative paths, not absolute ones.
=> Fix `dependabot.yml` to work with dev deps

lona/html/attribute_dict.py
``html.escape()`` assumes that ``value`` is a string (or some type it
can call ``.replace()`` on.
This fails for most other types than string.
Without this fix the following code breaks:
```
from lona.html import Option
op = Option('Text', value='text', bubble_up=True)
print(op)
```
```
LonaRuntimeWorker_0            ERROR    16:37:32.446884 lona.view_runtime Exception raised while running <__main__.MyView object at 0x7fba87f8a790>
Traceback (most recent call last):
File "/home/chris/work/Projects/intern/lag-intranet/env/lib/python3.9/site-packages/lona/view_runtime.py", line 318, in start
raw_response_dict = self.view.handle_request(self.request) or ''
File "/home/chris/work/Projects/intern/lag-intranet/demo.py", line 11, in handle_request
print(op)
File …
```
=> fix(html): Make sure value is a str()

doc/content/end-user-documentation/html.rst, lona/client/_lona/dom-renderer.js, lona/client/_lona/dom-updater.js, lona/client/_lona/window.js, lona/html/node.py, tests/static/test-widget.js, tests/test_widgets.py
Like discussed in https://github.com/lona-web-org/lona/discussions/228, this PR adds all features of `lona.html.Widget` into `lona.html.Node`, to make widgets obsolete, so they can be removed in Lona 2
=> html: make widgets obsolete

README.rst, doc/content/demos/counter/counter.py, doc/content/demos/daemonized-view/index.rst, doc/content/end-user-documentation/views.rst, doc/content/index.rst
Previously most examples in the documentation used the await API to retrieve input events. This API is meant for some special cases, like interactive, long-running wizards.
Also there was no clear distinction between daemonized- and multi-user views.
Users who are new to Lona, Python or Web in general (or all of them) might come to the conclusion that these are the APIs to use when creating a simple CRUD application.
This might work in simple test-cases, but will be very resource heavy with an actual user base.
This patch ports most examples to use callbacks to handle input events, and adds some clear warnings on the implications of the daemonize and the await APIs.
=> doc: make implications of awaiting input events and daemonizing clearer

tests/test_routing.py
tests/test_routing.py::TestReverseMatching::test_reverse_with_arg_and_optional_slash
/project/.tox/python/lib/python3.8/site-packages/_pytest/fixtures.py:900: PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future
release.
tests/test_routing.py::TestReverseMatching::test_reverse_with_arg_and_optional_slash is using nose-specific method: `setup(self)`
To remove this warning, rename it to `setup_method(self)`
See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
fixture_result = next(generator)
=> tests: routing: fix pytest deprecation warning

doc/content/end-user-documentation/html.rst, doc/content/end-user-documentation/settings.rst, lona/client/_lona/client/input-events.js, lona/client2/_lona/client2/input-events.js, lona/compat.py, lona/default_settings.py, lona/html/__init__.py, lona/html/data_binding/select.py, lona/html/data_binding/select2.py, lona/html/parsing.py, lona/server.py, tests/test_0001_html.py, tests/test_html_select.py, tests/test_html_select2.py
This is an improved version of #276.
This PR adds an improved version of `lona.html.Select`, called `lona.html.Select2`. The new API is much simpler than the old one, because it does not use magic properties to generate `lona.html.Option` nodes and their values, but lets the user create them himself. The type of `lona.html.Option2.value` was also fixed: The old version always converted all values to strings, which is surprising inconvenient.
To make `lona.html.Select` available, using HTML string parsing, without breaking compatibility, the new nodes only get used when a feature flag is set.
=> Add better implementation for `lona.html.Select`

lona/client/_lona/client/lona.js, lona/client2/_lona/client2/lona.js
This PR removes public class fields from both JavaScript clients, because this feature is not supported in Safari<14.1.
This produced issues on iPhone 6 and iPad mini 2, reported by @markusgritsch in #334.
=> client: remove public class fields

doc/content/tutorial/01-getting-started/index.rst
This section was a bit confusing, because import strings are only really relevant in Lona projects. Since the tutorial only uses scripts in its examples, it needed a bit of clarification, what import strings are meant for.
=> doc: tutorial: getting started: update import string section

lona/templates/lona/frontend.html
Having this meta tag is recommended e.g. here and here and improves viewport size on mobile devices.
=> templates: frontend: Add viewport meta tag

doc/content/tutorial/02-html/index.rst
There's a small typo in the code for 'Nodes Are Unique'
Should be:
>>> div
=> fixed typo in code for 'Nodes Are Unique'

lona/html/node_list.py, tests/REQUIREMENTS.test.txt, tests/test_performance.py
Here's a minimal workaround for the performance problem caused by NodeList.append() and a small test to prove it's now performing normally. See #401 for details.
=> Minimal fix for NodeList.append() and accompanying test

playwright.Dockerfile, pyproject.toml
This commit consists of two dependabot commits, which are squashed so the docker and the pip version match at all times.
build(deps): Bump playwright from v1.34.3-jammy to v1.35.0-jammy
Bumps playwright from v1.34.3-jammy to v1.35.0-jammy.
---
updated-dependencies:
- dependency-name: playwright dependency-type: direct:production ...
build(deps-dev): Bump playwright from 1.34.0 to 1.35.0
Bumps [playwright](https://github.com/Microsoft/playwright-python) from 1.34.0 to 1.35.0.
- [Release notes](https://github.com/Microsoft/playwright-python/releases)
- [Commits](https://github.com/Microsoft/playwright-python/compare/v1.34.0...v1.35.0)
---
updated-dependencies:
- dependency-name: playwright dependency-type: direct:production update-type: version-update:semver-minor ...
=> build: Bump playwright from 1.34 to 1.35

.github/workflows/ci.yml, Makefile, lona/command_line/collect_static.py, lona/command_line/handle_command_line.py, mypy.ini, pyproject.toml, tox.ini
Since 27. Jun 2023, Python 3.7 is end of life (https://endoflife.date/python). Thus, this patch removes support for this version.
=> python: drop support for 3.7

doc/content/api-reference/html.rst, lona/html/__init__.py, lona/html/parsing.py, lona/html/widgets.py
This PR renames `lona.html.parsing.html_string_to_node_list` to `lona.html.parse_html` to make it official API that will replace HTML parsing in `lona.html.HTML` and `lona.html.HTML2` (#268)
=> html: add parse_html

lona/client2/_lona/client2/rendering-engine.js, lona/logging.py, test_project/views/frontend/rendering.py, tests/test_0304_rendering.py
This PR fixes a rendering problem in client2 when moving nodes within a tree, and contains a patch to make client errors more readable in log
=> fix rendering issue

doc/content/api-reference/views.rst
- the non-interactive example returning JSON should not use the deprecated dictionary return
- a line of explanatory text for the Trailing Slash example (had to test if this actually worked as I suspected).
=> Deprecated example code, clarification

doc/content/tutorial/01-getting-started/index.rst, lona/app.py, lona/command_line/handle_command_line.py
If the default port 8080 is taken, you have to either change the app.run() or  use --port <PORTNUM> on every invocation of the program. When trying out examples I don't want to do the first and forget the second.
This patch allows you set the environment variables LONA_DEFAULT_HOST and LONA_DEFAULT_PORT in your shell. These override the built-in defaults ('localhost' resp. 8080), and are in turn overridden by arguments to ``app.run()`` and startup commandline parameters.
=> server: get default port optionally form environment var

doc/content/roadmap.rst, doc/settings.py
All entries and the format can be discussed
=> doc: add roadmap

lona/client/_lona/client/input-events.js, lona/client2/_lona/client2/input-events.js, tests/test_0305_requests.py
According to the documentation
(https://lona-web.org/1.x/api-reference/views.html#post ) it should be possible to submit a `<form>` using `POST` to an interactive lona view. Without this change this fails with a
`Uncaught ReferenceError: lona_window is not defined` in the browser.
This change fixes the missing reference and allows to use the `POST` method to submit data to the view.
=> client1 + client2: Fix `onsubmit` event handler to allow submitting forms

.github/workflows/ci.yml
Reverts lona-web-org/lona#483
This PR broke all test pipelines
=> Revert "build: Bump codecov/codecov-action from 3 to 4"

Makefile, doc/content/api-reference/html.rst, lona/client/_lona/client/input-events.js, lona/client2/_lona/client2/input-events.js, lona/html/__init__.py, lona/html/attribute_dict.py, lona/html/nodes/forms/radio_button.py, test_project/Makefile, test_project/views/events/change_events.py, test_project/views/events/inputs.py, tests/test_0204_html_radio_buttons.py, tests/test_0305_events.py
This PR adds initial support for HTML radio buttons (#229)
=> html: add radio buttons

lona/client2/_lona/client2/rendering-engine.js
Previously, the rendering of client 2 would crash when too many nodes were removed at the same time. This happened because the rendering engine method for removing a node, called the method for cleaning the node cache, and vice versa.
In theory that is correct and works, but if the amount of nodes that should be removed is big enough, the JavaScript call stack size will exceed the browsers limit.
This patch removes the dependency between the two methods and adds more careful cache cleaning calls.
Resolves #496
=> client2: rendering: fix call stack limit problems in node cache

doc/content/demos/daemonized-view/daemonized-view.py, lona/html/node.py, lona/html/nodes/forms/__init__.py, lona/html/nodes/forms/select.py, lona/html/parsing.py, lona/templating.py, lona/view.py, lona/warnings.py
add deprecation warning
add intermediary Lona_2_0_DeprecationWarning so only one warnings needs to be set for filtering.
update example code
=> views: issue warning on use of .daemonize

playwright.Dockerfile, pyproject.toml, tests/test_0302_responses.py, tests/test_0306_requests.py, tests/test_0307_history.py, tests/test_redirects.py, tests/test_redirects_from_event_handlers.py
Somewhere between Playwright 1.40 and 1.44, `Page.wait_for_url()` changed behavior. Now, only URLs, starting with wildcards, seem to work for our usecase.
I am not sure why that was changed, or why this is a problem in our test, but the change in this patch is in line with the documentation of `Page.wait_for_url()`, so it should be fine.
=> tests: playwright: bump from 1.44.0 to 1.44.0
