README.rst
doc/content/end-user-documentation/getting-started.rst
doc/content/index.rst

example broke, now example less broke

Fix single-file script examples

---

lona/html/nodes.py

Fixes #9.
There is no such method `remove` in attributes.

Use `del` keyword to remove attribute

---

doc/content/end-user-documentation/getting-started.rst
doc/content/end-user-documentation/html.rst
doc/content/end-user-documentation/lona-scripts.rst
doc/content/end-user-documentation/views.rst

Fix some typos in documentation.

Typos in doc

---

doc/content/cookbook/writing-a-daemon-view.rst
doc/content/end-user-documentation/frontends.rst

Fix some typos in documentation.

Typos in doc 2

---

doc/content/end-user-documentation/frontends.rst

Reference - https://flamingo-web.org/user/writing_content.html
fixes #12

Correct way of linking to other pages

---

pytest.ini
tox.ini

Fixes coverage

---

lona/html/attribute_list.py

html: attributes: optimisation: use set under the hood

---

Makefile
REQUIREMENTS.dev.txt
doc/plugins/pygments.py
doc/plugins/rst_setting.py
doc/plugins/toc_tree.py
flake8.ini
lona/__init__.py
lona/default_views.py
lona/events/__init__.py
lona/html/__init__.py
lona/html/node.py
lona/html/nodes.py
lona/html/parsing.py
lona/html/selector.py
lona/server.py
lona/settings.py
lona/view_runtime.py
lona/view_runtime_controller.py
test_project/middlewares.py
test_project/routes.py
test_project/views/events/non_node_events.py
test_project/views/frontend/widget_data.py
test_project/views/home.py
test_script/test_script.py
tests/test_0001_html.py
tox.ini

See https://github.com/plinss/flake8-noqa/

lint: use flake8-noqa plugin

---

Makefile
REQUIREMENTS.dev.txt
doc/content/how-to-contribute.rst
lona/default_routes.py
lona/default_settings.py
lona/html/attribute_list.py
lona/html/data_binding/inputs.py
lona/html/node.py
lona/protocol.py
lona/view.py
mypy.ini
tox.ini

Let's use [mypy](https://github.com/python/mypy). This PR does minimal changes to start:
* ~~add `make mypy`~~
* ~~rename github workflow `test` -> `ci`~~
* run mypy in ci (lint stage)
* run mypy on `make lint`
* add instructions to `How To Contribute`
* add minimal type annotations to pass mypy

Start using mypy

---

REQUIREMENTS.dev.txt
lona/html/attribute_dict.py
lona/server.py
tox.ini

See https://github.com/zheller/flake8-quotes/

lint: use flake8-quotes plugin

---

REQUIREMENTS.dev.txt
lona/html/attribute_list.py
lona/shell/commands/lona_settings.py
tox.ini

See https://github.com/adamchainz/flake8-comprehensions

lint: use flake8-comprehensions plugin

---

REQUIREMENTS.dev.txt
flake8.ini
lona/client_pre_compiler.py
lona/command_line/run_server.py
lona/default_views.py
lona/html/parsing.py
lona/middleware_controller.py
lona/server.py
lona/settings.py
lona/view_loader.py
lona/view_runtime.py
tox.ini

See https://github.com/globality-corp/flake8-logging-format

lint: use flake8-logging-format plugin

---

REQUIREMENTS.dev.txt
tests/test_0001_html.py
tests/test_routing.py
tox.ini

See https://github.com/m-burst/flake8-pytest-style

lint: use flake8-pytest-style plugin

---

REQUIREMENTS.dev.txt
flake8.ini
lona/middlewares/sessions.py
lona/shell/commands/lona_middlewares.py
lona/shell/commands/lona_static_files.py
lona/shell/commands/lona_templates.py
lona/view_runtime.py
lona/worker_pool.py
tox.ini

See https://github.com/PyCQA/flake8-bugbear

lint: use flake8-bugbear plugin

---

lona/html/parsing.py
tests/test_0001_html.py

html: fix parsing of Textarea.value

---

README.rst

Works in conjunction with #103

doc: readme: add ci badge

---

.isort.cfg

@fscherf Sorry I forgot to push changes in #106

dev: remove default isort configs

---

doc/content/demos/bootstrap-5-confirmation-popup/bootstrap-5-confirmation-popup.py
doc/content/demos/chartjs-click-analyzer/chartjs-click-analyzer.py
doc/content/demos/counter/counter.py
doc/content/demos/daemonized-view/daemonized-view.py
doc/plugins/pygments.py
doc/plugins/rst_setting.py
doc/plugins/toc_tree.py
lona/app.py
lona/html/attribute_dict.py
lona/html/data_binding/select.py
lona/html/node_list.py
lona/html/widget_data.py
lona/middleware_controller.py
lona/response_parser.py
lona/routing.py
lona/server.py
lona/static_file_loader.py
lona/view_runtime.py
lona/view_runtime_controller.py
test_project/views/events/callbacks.py
test_project/views/events/change_events.py
test_project/views/events/class_based_view.py
test_project/views/events/click_events.py
test_project/views/events/data_binding.py
test_project/views/events/event_bubbling.py
test_project/views/multi_user/multi_user_chat.py
test_project/views/view_types/async_view.py
tests/conftest.py
tests/test_0001_html.py
tox.ini

@fscherf What do you think about this [linter](https://github.com/PyCQA/flake8-commas)?

lint: use flake8-commas plugin

---

lona/html/attribute_dict.py
tests/test_0001_html.py

html: attributes: use html escape

---

tox.ini

Let's use [flake8-mutable](https://github.com/ebeweber/flake8-mutable).

lint: use flake8-mutable plugin

---

flake8.ini
lona/logging.py
lona/response_parser.py
lona/routing.py
lona/static_files.py
tox.ini

Let's use [flake8-use-fstring](https://github.com/MichaelKim0407/flake8-use-fstring)

lint: use flake8-use-fstring plugin

---

lona/static_file_loader.py

static files: fix handling of linked flag

---

lona/static_file_loader.py
tests/test_static_files.py

fix(static files): issue when non-linked file was not served

---

doc/content/end-user-documentation/views.rst
lona/client_pre_compiler.py
lona/html/abstract_node.py
lona/imports.py
lona/server.py
lona/static_file_loader.py
lona/static_files.py
lona/view.py
lona/view_loader.py
tests/test_static_files.py
tests/test_static_files_view.py
tests/test_static_files_widget.py

Closes #95
* A lot of refactoring
* Some minor fixes
* Add logging on non-unique names
* Discover static files in views
* Add tests

Define `STATIC_FILES` in `LonaView` like in `Widget`

---

lona/app.py
lona/default_routes.py
lona/default_settings.py
lona/html/abstract_node.py
lona/html/data_binding/inputs.py
lona/html/node.py
lona/html/parsing.py
lona/imports.py
lona/protocol.py
lona/server.py
lona/static_file_loader.py
lona/view.py
lona/view_loader.py
lona/view_runtime.py
tests/conftest.py

types: use new type annotation syntax

---

.coveragerc
pytest.ini
tox.ini

tests: fix coverage

---

lona/app.py
lona/command_line/handle_command_line.py
lona/events/view_event.py
lona/html/document.py
lona/logging.py
lona/server.py
lona/view.py
lona/view_runtime_controller.py
pytest.ini
tests/test_view_events.py
tox.ini

This pull-request adds a new events that can be send between views for communication. More details: #79

Add view events for better multi-user views

---

doc/content/cookbook/integrating-a-frontend-library.rst
doc/content/end-user-documentation/html.rst
doc/settings.py

doc: cookbook: add article on how to add a frontend library

---

doc/content/end-user-documentation/html.rst

See https://github.com/lona-web-org/lona/discussions/144

docs(html): add debouncing to input_delay description

---

lona/command_line/run_server.py

feat(server): add compatibilty with aiohttp 3.8

---

doc/content/end-user-documentation/html.rst
lona/client/input-events.js
lona/html/data_binding/inputs.py
tests/test_0001_html.py
tests/test_number_input.py

This PR contains all changes regarding ``lona.html.NumberInput`` that @maratori and i agreed on in #102, and a test

html: rework number input

---

lona/client/context.js
lona/client/window.js
lona/routing.py
tests/test_routing.py

This PR contains two little bugfixes: One for the Javascript client, and one regarding routing problems

small bugfixes

---

lona/logging.py

This PR fixes #181 by adding support for syslog priorities

feat(logging): add support for syslog priorities

---

doc/content/end-user-documentation/lona-scripts.rst
doc/content/end-user-documentation/views.rst
lona/app.py
lona/errors.py
lona/view_runtime.py
tests/test_403_forbidden_errors.py
tests/test_404_not_found_errors.py
tests/test_500_internal_errors.py

This PR brings support for ``NotFoundError`` and decorators for adding error views in Lona scripts

improve error views

---

doc/content/end-user-documentation/settings.rst
lona/default_settings.py
lona/templating.py
test_project/settings.py
test_project/templates/template_response.html
tests/test_template_filters.py

This PR adds support for Jinja2 template filters, some documentation and a test

templating: add support for template filters

---

doc/content/end-user-documentation/html.rst

Signed-off-by: Chris Fiege <cfi@pengutronix.de>

doc/html: Fix camel case in import for checkbox

---

.coveragerc
doc/REQUIREMENTS.txt
doc/content/end-user-documentation/server.rst
doc/content/end-user-documentation/testing.rst
doc/content/end-user-documentation/views.rst
doc/plugins/api_doc.py
doc/settings.py
lona/__init__.py
lona/client_pre_compiler.py
lona/connection.py
lona/events/view_event.py
lona/html/selector.py
lona/pytest.py
lona/server.py
lona/static_file_loader.py
lona/view.py
lona/view_runtime.py
lona/view_runtime_controller.py
tests/test_0001_html.py

This PR adds some new tests, some new testing helper and documentation.

improve testing

---

lona/client/_lona/context.js
lona/client/_lona/dom-renderer.js

This PR fixes some uninitialized variable and variable name issues

client: fix uninitialized variables

---

Makefile
doc/plugins/toc_tree.py
lona/html/attribute_dict.py
lona/html/data_binding/inputs.py
lona/logging.py
lona/middlewares/sessions.py
lona/protocol.py
lona/pytest.py
lona/response_parser.py
lona/server.py
lona/shell/commands/lona_views.py
lona/static_file_loader.py
lona/view_loader.py
lona/view_runtime.py
lona/view_runtime_controller.py
lona/worker_pool.py
test_project/views/events/non_node_events.py
test_project/views/home.py
test_project/views/view_types/form_view.py
tests/REQUIREMENTS.lint.txt
tests/test_0001_html.py

This PR should fix all current linting problems uncovered by dependabot

dependabot fixes

---

.github/dependabot.yml

Now it should be fine!
Closes #284

Fixes #284

---

doc/content/end-user-documentation/views.rst
lona/client/_lona/context.js
lona/client/_lona/input-events.js
lona/client/_lona/window-shim.js
lona/events/input_event.py
lona/html/abstract_node.py
lona/html/node.py
lona/html/node_list.py
lona/html/parsing.py
test_project/Makefile
test_project/templates/lona/frontend.html
tests/test_0001_html.py
tests/test_click_events.py

This PR contains multiple fixes concerning the HTML API and input event API, and some refactoring

html and input event fixes

---

lona/client/_lona/dom-updater.js
test_project/routes.py
test_project/views/frontend/rendering.py
test_project/views/home.py
tests/test_rendering.py

This PR adds a test to the test suite that tests the client side rendering in a browser test.
This PR also contains a fix for the client side rendering code, to make the new test succeed in the first place.
The new test is a new version of https://github.com/lona-web-org/lona/commit/6543accea60379f95a8f4ba73a84be8aca85d394 that now also covers CSS style manipulation.

setup rendering tests

---

doc/content/changelog.rst
lona/__init__.py
lona/view.py
lona/view_runtime.py
lona/view_runtime_controller.py
pyproject.toml
tests/test_daemon_views.py
tests/test_redirects_from_event_handlers.py

This PR fixes multiple regression fixes, itroduced in 1.12

1.12 regression fixes

---

doc/content/changelog.rst
lona/__init__.py
lona/view_runtime.py
pyproject.toml
tests/test_daemon_views.py

fix daemon views

---

doc/content/tutorial/01-getting-started/index.rst
doc/content/tutorial/02-html/index.rst
doc/content/tutorial/03-events/index.rst
doc/content/tutorial/04-routing/index.rst
doc/content/tutorial/05-responses/index.rst
doc/content/tutorial/06-daemon-views/index.rst
doc/content/tutorial/07-state/index.rst
doc/content/tutorial/08-middlewares/index.rst
doc/content/tutorial/09-static-files/index.rst
doc/content/tutorial/10-widgets/index.rst
doc/content/tutorial/11-frontends/index.rst
doc/settings.py

This PR fixes some typos and wording problems in the tutorial. It also adds some nicer numbering

doc: tutorial fixes

---

doc/content/api-reference/server.rst
lona/server.py

This patch updates the documentation for `Server.run_coroutine_sync()` and `Server.run_function_async()`

doc: server: update method documentation

---

doc/content/tutorial/06-daemon-views/index.rst
doc/content/tutorial/07-state/index.rst
doc/content/tutorial/08-middlewares/index.rst
doc/content/tutorial/09-static-files/index.rst
doc/content/tutorial/10-widgets/index.rst
doc/content/tutorial/11-frontends/index.rst

This PR fixes some typos and wording in the tutorial chapters 6-11.

Proofreading

---

doc/content/demos/function-plotter/function-plotter.py

Refactored code to be more DRY and more generic.

doc: demos: Function Plotter stylistic improvements

---

lona/html/abstract_node.py
lona/html/node.py
lona/html/text_node.py
lona/html/widget.py
lona/html/widget_data.py

This PR improves the performance of node comparisons, by replacing the previously used JSON serialization with simple checks

improve node compare performance

---

doc/content/tutorial/03-events/example-2.py

Index.handle_click is never used in this example, looks like it is a remnant of copy-paste of example-1.py

remove unused method

---

doc/content/api-reference/deployment.rst

minor doc typo
